### ISSUE TITLE
unable to import /training/car_workspace.json

### ISSUE THREAD

**Issue by kmohanarangam** [watson-developer-cloud/conversation-simple#103] opened 2017-03-27 02:04 UTC
Hi,
When importing the training file, bluemix is throwing "incorrect syntax" error. 
See http://imgur.com/a/PARfR

Edit: Importing from Windows 64

**Comment by germanattanasio** [comment] 2017-03-27 20:29
I think this is a duplicate of #100

**Closed** 2017-03-27 20:29 UTC
Labels: duplicate
